// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // mySidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorials',
  //     items: [
  //       {
  //         type: 'doc',
  //         id: 'Cryptography'
  //       }
  //     ],
  //   },
  // ],
};

module.exports = sidebars;
