name = "polykey-docs-dev"
main = "server/index.ts"
compatibility_date = "2022-07-28"
usage_model = "bundled"
workers_dev = true
[site]
  bucket = "./public"

[env.production]
  name = "polykey-docs"
  routes = ["polykey.com/docs", "polykey.com/docs/*"]
  workers_dev = false
