name = "polykey-docs-dev"
main = "server/worker.ts"
send_metrics = false
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
routes = [
  "dev.polykey.com/docs",
  "dev.polykey.com/docs/*"
]
[site]
  bucket = "./public"

[env.staging]
  name = "polykey-docs-staging"
  routes = [
    "staging.polykey.com/docs",
    "staging.polykey.com/docs/*"
  ]

[env.master]
  name = "polykey-docs"
  routes = [
    "polykey.com/docs",
    "polykey.com/docs/*"
  ]
