name: Clean

on:
  pull_request:
    types:
      - closed

jobs:
  check-deployment-stop:
    name: "Check / Deployment Stop"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matrixai/github-runner
    concurrency:
      group: check-deployment-stop
      cancel-in-progress: false
    environment: feature
    if: startsWith(github.head_ref, 'feature')
    steps:
      - uses: actions/checkout@v4
      - name: Run deployment
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          echo 'Perform service deployment for feature'
          nix develop .#ci --command bash -c $'
          wrangler delete --name "polykey-docs-dev-$GITHUB_HEAD_REF" --force
          '
